/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_java_tools_GameTool */
#include "jni.h"
#ifndef _Included_com_java_tools_GameTool
#define _Included_com_java_tools_GameTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_tools_GameTool
 * Method:    cls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_java_tools_GameTool_cls
  (JNIEnv *, jclass);

/*
 * Class:     com_java_tools_GameTool
 * Method:    randomReturnBoolean
 * Signature: (ID)Z
 */
JNIEXPORT jboolean JNICALL Java_com_java_tools_GameTool_randomReturnBoolean
  (JNIEnv *, jclass, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
