/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javaLogic_Tools_GameTool */

#ifndef _Included_javaLogic_Tools_GameTool
#define _Included_javaLogic_Tools_GameTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javaLogic_Tools_GameTool
 * Method:    cls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javaLogic_Tools_GameTool_cls
  (JNIEnv *, jclass);

/*
 * Class:     javaLogic_Tools_GameTool
 * Method:    print
 * Signature: ()V
 */

#ifdef __cplusplus
}
#endif
#endif
